name: Terraform Workflow

on:
push:
branches:
- main
workflow_dispatch:

jobs:
terraform:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout Terraform Repo
    uses: actions/checkout@v4
    with:
      repository: CloudDevopsRavina/Terraform
      path: Terraform

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  # Optional: AWS credentials
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1

  - name: Terraform Init
    working-directory: Terraform/Day-2
    run: terraform init

  - name: Terraform Plan
    working-directory: Terraform/Day-2
    run: terraform plan

  - name: Terraform Apply
    if: github.ref == 'refs/heads/main'
    working-directory: Terraform/Day-2
    run: terraform apply -auto-approve
```
