name: Terraform Workflow

on:
push:
branches:
- main
workflow_dispatch:

jobs:
terraform:
runs-on: ubuntu-latest


steps:
  - name: Checkout Terraform Repo
    uses: actions/checkout@v4
    with:
      repository: CloudDevopsRavina/Terraform
      path: Terraform

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Init
    working-directory: Terraform/Day-2
    run: terraform init

  - name: Terraform Plan
    working-directory: Terraform/Day-2
    run: terraform plan

  - name: Terraform Apply
    if: github.ref == 'refs/heads/main'
    working-directory: Terraform/Day-2
    run: terraform apply -auto-approve

